version: "3.4"

services:
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: star-wars
  node:
    restart: always
    build:
      context: .
      target: dev_build
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      MONGODB_URI: mongodb://db:27017/star-wars
